version: "3.8"

services:
  ibicos-backend:
    build:
      context: .
    ports:
      - 8080:8080
      - 8000:8000
    environment:
      - SERVER_PORT=8080
      - MYSQL_URL=jdbc:mysql://mysqlserver/classificados_db
      - IBICOS_SIGNING_JWT_KEY=test
      - IBICOS_EMAIL_PASSWORD=test
      - IBICOS_EMAIL_USERNAME=test
      - MYSQL-USER=

    volumes:
      - ./:/ibicos_backend
    command: ./mvnw spring-boot:run -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0.23
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=classificados_db
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

volumes:
  mysql_data:
  mysql_config:
